# Generated by Django 5.1.1 on 2024-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_place', models.CharField(max_length=200)),
                ('patient_phone', models.TextField(max_length=200)),
                ('patient_dicese', models.CharField(max_length=200)),
                ('how_meny_day_start_your_dicese', models.CharField(max_length=200)),
            ],
        ),
    ]
